### ISSUE TITLE
ocl/deployer-gnulinux missing

### ISSUE THREAD

**Issue by schwarzp93** [orocos-toolchain/ocl#79]
Hi guys :)

sorry, if my question may be a bit silly, but I'm pretty new th the world of orocos ...

I want to use SOEM to communicate via EtherCAT between a Festo CPX-FB37 bus node an an Ubuntu 16.04 system.

I followed the instructions here (https://github.com/orocos/rtt_ros_integration) to install orocos-toolchain and rtt_integration. Both times, I used "-b toolchain-2.9" when cloning.
After that, I cloned this repository https://github.com/orocos/rtt_soem (also tried this one https://github.com/keivanzavari/rtt_soem). When I want to use the soem_master_test.launch file, I get the following Error:

ERROR: cannot launch node of type [ocl/deployer-gnulinux]: can't locate node [deployer-gnulinux] in package [ocl]

What could be the problem here?

Thanks in advance!

Regards, Philipp

**Comment by meyerj** [comment]
`rtt` and `ocl` are not ROS packages and most traces of ROS have been removed in version 2.7 (with the transition to catkin as a build-tool), or even earlier. The OCL binaries, like `deployer-gnulinux`, are installed to the global `bin` directory, where they cannot be found directly by ROS tools like `rosrun` or `roslaunch`. Only package [rtt_ros](https://github.com/orocos/rtt_ros_integration/tree/toolchain-2.9/rtt_ros) provides script wrappers that are installed to the package binary destination `lib/rtt_ros`, where they will be found (formerly `${PROJECT_SOURCE_DIR}/bin`).

I assume the launch files in `rtt_soem` date back to the time before these commits and have never been updated. Please try to replace `<node pkg="ocl" type="deployer-gnulinux" ...` by `<node pkg="ocl" pkg="rtt_ros" type="deployer" ...` (without `-gnulinux`), and ideally add `rtt_ros` as a `<run_depend>` to `package.xml`.

It would be possible to additionally install the utility scripts or wrappers in `ocl` to the `lib/ocl` destination, which would fix the backwards-compatibility issue at the minimal cost of installing some additional scripts for non-ROS users. But because other functionality like the recursive import of ROS packages that provide component or plugin libraries has also been moved to `rtt_ros`, you might have to depend on and use that package anyway in more complex deployments using ROS tools.

Related commits:
- https://github.com/orocos-toolchain/ocl/commit/24479d2ae3959f4b64433cae0081091154b69704
- https://github.com/orocos-toolchain/ocl/commit/474de621db1eda161f9b7cbf5133ccf4706918ad
- https://github.com/orocos-toolchain/ocl/commit/0a677622049100d450d9b9b180fc48497bb74c0e

**Comment by schwarzp93** [comment]
perfect answer, thanks a lot! :)
